### ISSUE TITLE
Buttons requested

### ISSUE THREAD

**Issue by kgold2** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#23]
Build: Equivalent to C-S-B <RET>
Run: Equivalent to C-F5
Debug: Equivalent to F5

**Comment by scotthardwick** [comment]
Build - workbench.action.tasks.build
Run - workbench.action.debug.run
Debug - workbench.action.debug.start or workbench.action.debug.continue... F5 chooses between them depending on value of inDebugMode

**Comment by GorvGoyl** [comment]
Duplicate of #14
