### ISSUE TITLE
menu Bug

### ISSUE THREAD

**Issue by tmmaribell** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#25]
This menu does not work in text edit mode

![2020-09-06_094806](https://user-images.githubusercontent.com/68552762/92319960-67da3a80-f026-11ea-8ce6-b65c44c5985d.png)

**Comment by GorvGoyl** [comment]
are you talking about that 3 dots menu? it is not from this extension, it's built-in to the vscode. you can test it by disabling the extension.

**Comment by tmmaribell** [comment]
Disabling the menu extension works well, but if you enable it again, it does not work when editing text

**Comment by tmmaribell** [comment]
https://drive.google.com/file/d/1D-YvESO5rdr1QVnrCetj63STLWg_xg1p/view?usp=sharing

**Comment by GorvGoyl** [comment]
thanks for that video, that helped! It's a bug and will fix it.

**Comment by GorvGoyl** [comment]
This is a bug from vscode itself https://github.com/microsoft/vscode/issues/106357 , hopefully they will fix in next release.

**Comment by tmmaribell** [comment]
thanks, Everything works great
