### ISSUE TITLE
Make a config namespace for your extension

### ISSUE THREAD

**Issue by bbugl** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#29]
Every extension that I know of uses the config schema "namespace.[subNamespace.]config". This has the nice property of being able to sort the settings file and have the configs grouped together. Would this be possible for your extension?

**Comment by GorvGoyl** [comment]
I think I tried that approach before but it seems this extension works differently from others and managing extension setting from config won't work. I could be wrong, so, if you've come across any other similar extension which works that way or you know some workaround do let me know.
