### ISSUE TITLE
Add multiple line "comment" button

### ISSUE THREAD

**Issue by baolenmeng** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#35]
Hello, I'm happy to use your shortcut extension!
Could you add one button for "comment"?
But it's challenging. Different languages have different comment ways.
I frequently code by python and type by LaTeX.
Thank you in advance!

**Comment by baolenmeng** [comment]
So one more button for "uncomment".

**Comment by GorvGoyl** [comment]
hey, it's already there. check settings
