### ISSUE TITLE
FR: please co-publish on open-vsx

### ISSUE THREAD

**Issue by GitMensch** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#36]
For details see [Publishing Extensions on open-vsx.org](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension). It would be good to have this extension not only in the ms marketplace but also available in a place that does not explicit forbid to use it with anything else than a Visual Studio product or a browser.
Currently there is no real [menu extension](https://open-vsx.org/?search=menu) found in the Open VSX registry.

**Comment by GorvGoyl** [comment]
Sure, will check the process
