### ISSUE TITLE
Can the svg icons be dropped in favor of vscode icons?

### ISSUE THREAD

**Issue by GitMensch** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#39]
see https://code.visualstudio.com/api/references/icons-in-labels

Doing this would make adding new entries much easier and alo allow the icons to match the theme automatically.

**Comment by GorvGoyl** [comment]
Thanks, I checked the list but couldn't find some icons for the extension settings so have to rely on svg icons. I think VSCode icons will be useful once this extension allow users to add their own buttons/commands.
