### ISSUE TITLE
FR: Different buttons for different file types

### ISSUE THREAD

**Issue by JohnVeness** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#57]
I don't know if this is possible, but it would be very useful to be able to configure different buttons for different file types. For example, it would be useful to have different buttons when I'm editing Markdown files compared to when editing .cpp files.

Thanks for this extension!

**Comment by GitMensch** [comment]
Isn't that possible already? Please try to configure [language specific settings](https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings) and report back, it would likely be useful to document that in the readme, the python example would be nice.

**Comment by JohnVeness** [comment]
Thanks for the link. I was hoping for something a bit more graphical!

**Comment by GitMensch** [comment]
If you find or create an issue at vscode about "file type specific settings UI" I'd upvote it - but that's a general issue and not related to this extension.

**Comment by GorvGoyl** [comment]
closing due to out-of-scope
