### ISSUE TITLE
Question "Maybe Non-Issue"  - Why does toolbar wrap?

### ISSUE THREAD

**Issue by CodeChaser** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#59]
My monitors are plenty large enough to handle all of the items that I have selected, but many wrap so I hit the "..." to get to them.  Any ideas what setting I have missed.  Here is are a couple of screen shots.

This shows that there is plenty of space
![image](https://user-images.githubusercontent.com/3975823/126549015-5eed17ca-67a6-41ac-b368-aefdc5f6780c.png)

This shows the wrapped items
![image](https://user-images.githubusercontent.com/3975823/126549112-4b1febab-f1f6-4f44-8a15-967efc7e5494.png)

Tom

**Comment by RealDeviil** [comment]
First of all, thank you for your hard work on this extension. It is very useful.

That said, I am having the same issue as the OP.

Available buttons should fill up the available title bar real estate, and only wrap if there is not enough available space.

I have searched for an extension or VS Code setting to modify this behavior, but I can't find one.

So, either such a setting exists and I can't find it, or it does not exist at all. If the latter case is true, then I hope the developer(s) will consider adding more flexibility to the UI in this regard.

Thanks again.

**Comment by Kenobi-the-2nd** [comment]
This is a limitation inherent in VS Code. Only 9 buttons are allowed at one time in the action toolbar. Any beyond this will overflow into the "More Actions..." dropdown to the far right.

**Comment by RealDeviil** [comment]
@Kenobi-the-2nd Thank you! After using VS Code more, I can confirm that you are correct. 

This issue should be closed.
