### ISSUE TITLE
Place buttons in the breadcrumbs area

### ISSUE THREAD

**Issue by flowstate247** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#63]
As seen in this comment: https://github.com/GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension/issues/46#issuecomment-804142066

That would be great as it wouldn't steal valuable space in the tabs area.

**Comment by GitMensch** [comment]
The original screenshot come from @TauerOne with his local-adjusted extension. We'd need a PR to review and integrate it.

**Comment by GitMensch** [comment]
You'd need to request that from the vscode ui team, the "as seen" is a manual hack of .css and .js files shipped with vscode.
As there is no option to do this via an extension I suggest to close this issue.

**Comment by GorvGoyl** [comment]
closing due to out-of-scope
