### ISSUE TITLE
Open Settings icon appears twice on shortcut bar

### ISSUE THREAD

**Issue by mileso** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#68]
The first time I enabled "Open Settings" it appeared once.  After adding a couple custom commands and turing various buttons off and on "Open Settings" now appears twice when enabled.

Note: after installing the Shorcut Menu Bar extension I installed a couple other UI extensions (e.g. customizeUI) but the issue started before these extensions were installed.

Here is an image of the duplicated icons: 
<img width="216" alt="VSCodeShortcuts" src="https://user-images.githubusercontent.com/857624/147681880-a675285f-7cda-41eb-b689-5ec2e6a1e209.png">
Here is my settings file: [settings.json.txt](https://github.com/GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension/files/7789710/settings.json.txt)

**Comment by GitMensch** [comment]
I guess a restart of vscode yield the same result?

**Comment by GorvGoyl** [comment]
thanks for reporting, there were duplicate commands in JSON file and I fixed them. Watch out for the upcoming release.

**Comment by pgnd** [comment]
@GorvGoyl 
ping
any chance of a release -- even if just to clean up this duplication?

**Comment by GorvGoyl** [comment]
huh I thought I had released this version on marketplace. thanks for the ping, will release this week.
